### ISSUE TITLE
Add (default) virtual destructor

### ISSUE THREAD

**Issue by aromanro** [benhoyt/protothreads-cpp#7]
Since Protothread is an abstract class and one must derive from it and implement `Run`, it should have a virtual destructor.

**Comment by benhoyt** [comment]
Hi @aromanro, it's been a while since I've done C++ seriously. Can you give a concrete protothread example where this would matter?

To fix it, I guess it'd be a matter of adding `virtual ~Protothread() {}` to the `public` section of the class?

Or, should we make the destructor protected and non-virtual? Do we even need to allow "polymorphic deletion through a base poitner"? See discussion at http://www.gotw.ca/publications/mill18.htm, which says:

"Either: a) you want to allow polymorphic deletion through a base pointer, in which case the destructor must be virtual and public; or b) you don't, in which case the destructor should be nonvirtual and protected, the latter to prevent the unwanted usage."

**Comment by aromanro** [comment]
It would matter anywhere you have several classes derived from Protothread, but in order to handle them 'the same', you use Protothread pointers. Deleting them could result in leaks. Here is an explanation on stackoverflow: https://stackoverflow.com/questions/461203/when-to-use-virtual-destructors

I guess having a public 'virtual ~Protothread() = default;' should be enough.

I did the change in this pull request for a repo that uses Protothreads: https://github.com/luteberget/simcpp/pull/5

**Comment by benhoyt** [comment]
How does https://github.com/benhoyt/protothreads-cpp/pull/8 look? I preferred old-school `{ }` over `= default` to keep it simple (no need for C++11 here).

**Comment by aromanro** [comment]
It's perfectly fine that way, too :)
